name: engademy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  flutter_dotenv: ^5.1.0
  http: ^1.2.1 # Added for direct API calls

  # For State Management
  provider: ^6.1.2

  # For modern fonts
  google_fonts: ^6.2.1

  google_generative_ai: ^0.4.0 

  cupertino_icons: ^1.0.6

  # For skeleton loading
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
